services:
  controller:
    build:
      context: .
      dockerfile: Dockerfile.controller
    ports:
      - "15510:22"
    networks:
      - ssh

  target1:
    build:
      context: .
      dockerfile: Dockerfile.target
    ports:
      - "15511:22"
    networks:
      - ssh

  target2:
    build:
      context: .
      dockerfile: Dockerfile.target
    ports:
      - "15512:22"
    networks:
      - ssh

networks:
  ssh:
    driver: bridge
