FROM ubuntu:22.04

WORKDIR /usr/app

RUN apt-get update && \
    apt-get install -y netcat iputils-ping openssh-client openssh-server software-properties-common && \
    add-apt-repository -y --update ppa:ansible/ansible && \
    apt-get install -y ansible && \
    mkdir /var/run/sshd && \
    chmod 0755 /var/run/sshd

COPY . .
COPY ansible.cfg /etc/ansible/

EXPOSE 22

ENTRYPOINT service ssh restart && tail -f /dev/null
