---
- name: Copy file to target servers
  hosts: all
  tasks:
    - name: Copy file
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/../tmp-files/test-file.txt"
        dest: "/home/vince/foo.conf"
