name: Yaml Lint
on:
  pull_request:
    paths:
      - "**.yml"
      - "**.yaml"
  push:
    paths:
      - "**.yml"
      - "**.yaml"
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run yaml-lint
        uses: ibiqlik/action-yamllint@v3
        with:
          config_file: .yamllint.yml
          file_or_dir: "playbooks/"
